language: python

python:
  - '3.6'

services:
  - postgresql

before_install:
  - export DJANGO_SETTINGS_MODULE=uks.settings

install:
  - pip install -r requirements.txt

before_script:
  - psql -c "CREATE DATABASE mydb;" -U postgres

script:
  - python manage.py check
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py test projects/tests
  - python manage.py test milestones/tests
  - python manage.py test events/tests
  


